[package]
name = "monetdb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
array-macro = "2.1.8"
enum-utils = "0.1.2"
thiserror = "1.0.63"
url = "2.5.2"

[dev-dependencies]
bstr = "1.10.0"
itertools = "0.13.0"
