# SPDX-License-Identifier: MPL-2.0
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0.  If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright 2024 MonetDB Foundation

# Run doc tests, unit tests and clippy on Linux, Windows and MacOS
name: Unit tests

on:
  push:
    branch:
    pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:

  platform:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo clippy --tests -- -D warnings
      - run: cargo clippy --tests --no-default-features -- -D warnings
      - run: cargo clippy --tests --all-features -- -D warnings

      - run: cargo test --doc
      - run: cargo test --doc --no-default-features
      - run: cargo test --doc --all-features

      - run: cargo test --lib --examples
      - run: cargo test --lib --examples --no-default-features
      - run: cargo test --lib --examples --all-features

      - run: cargo tree
